### ISSUE TITLE
the param specificepithet shouldn't represent the binomial/trinomial species name

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#19]
http://rs.tdwg.org/dwc/terms/#specificEpithet - so change to `species` - in one or more fxns, can't remember which ones

**Comment by Pika8tona** [comment]
Maybe the documentation for searchbyterm() should be more clear but it says "Taxonomic species" (parallel with "Taxonomic genus" just below that), not anything about a binomial.  I think "species" is often assumed to mean the binomial, so "specificEpithet" is more...uh...specfic?  John Wieczorek should weigh in.

Chris Ray
University of Colorado-Boulder
cray@colorado.edu
303-459-0176 / 303-489-8863
________________________________________

**Comment by sckott** [comment]
Right, so _taxonomic species_ should be the binomial _Homo sapiens_, whereas _sapiens_ would be the specific epithet. Right? I think we just need to change `specificEpithet ` to `species`

**Comment by Pika8tona** [comment]
Since specificepithet is defined as the "species" part of the binomial "Genus species", while "species" (not a dwc term) in common usage often implies the full binomial, I guess I would fix this by changing the documentation rather than the terms.  Right now, the doc says "specificepithet = Taxonomic species" and "genus = Taxonomic genus", etc. (I added "Taxonomic" to avoid "genus = genus", etc.).  We could change the first term definition to "specificepithet = Taxonomic species; e.g., 'leo' in 'Panthera leo' "?
 
Chris Ray
University of Colorado-Boulder
cray@colorado.edu
303-459-0176 / 303-489-8863
________________________________________
