### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by maelle** [ropensci/rvertnet#71]
(or new maintainer _team_)

This package was archived on GitHub but not on CRAN.
If someone has interest in maintaining it, it won't be archived on CRAN.
We'd transfer it back to the ropensci GitHub organization.

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci-archive/admin

**Comment by maelle** [comment]
cc @zachary-foster

**Comment by willgearty** [comment]
Maybe...

**Comment by maelle** [comment]
@willgearty did you have time to think about maintaining this package? No pressure :innocent:

**Comment by willgearty** [comment]
Does it need any work, or does it just need a maintainer? I don't really have any time to work on another package right now, but if it just needs someone to watch over it, I probably could manage that.

**Comment by maelle** [comment]
@sckott do you remember whether the package used to work before you decided to archive it?

**Comment by sckott** [comment]
dont remember, but 

- r cmd check looks good
- examples threw a few errors, but those could be easy to fix, just don't know
- `make test` runs fine except for a ggplot2 deprecation that needs to be fixed 
- `VCR_TURN_OFF=true make test`  runs the same as above, which is a good sign because it does real HTTP requests and those still all work, whereas `make test` is using test fixtures

I'd probably recreate all the test fixtures too

**Comment by maelle** [comment]
Thanks @sckott!

@willgearty does this help?

**Comment by willgearty** [comment]
Unfortunately, I don't think I can commit to this right now, sorry.
